### ISSUE TITLE
Change default Credentials

### ISSUE THREAD

**Issue by mbrunn** [ByteProTips/Guacamole_Ansible#3]
Hello there,
I am installing Guacamole on a VM in Azure by using Terraform and wanted to change the default credentials.
Can they be set during the installation process?
I cannot find the [user-mapping-xml](https://guacamole.apache.org/doc/gug/configuring-guacamole.html#user-mapping-xml) on the system.
KR
Martin

**Comment by ByteProTips** [comment]
Hi,

The user-mapping-xml file is normally for simple guacamole deployments, where each user login is tied to a single remote connection of some kind.  This Ansible script instead configures Guacamole with a database backend to allow users to have one or many connections configured.  It also allows setting up/deleting configurations via the web UI.

If you wanted to change the admin password automatically during deployment, you could run a SQL query to update the guacadmin password.

Not sure if this helps/answers your question.
